from app.core.database import Base
from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Text
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import JSONB

class Asset(Base):

    __tablename__ = "assets"

    id = Column(Integer, primary_key=True)
    #user table
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    #file key for s3
    file_key = Column(Text, nullable=False)
    #AI pipeline status 
    status = Column(String, default="pending")
    #captions generated by AI pipeline
    captions = Column(Text, nullable=True)
    #metadata tags
    tags = Column(JSONB, nullable=True)
    #timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())
