from app.core.database import Base
from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Text, Float
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import JSONB


class Asset(Base):

    __tablename__ = "assets"

    id = Column(Integer, primary_key=True)
    #user table
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    #file key for s3
    file_key = Column(Text, nullable=False)
    #AI pipeline status 
    status = Column(String, default="pending")
    #captions generated by AI pipeline
    captions = Column(Text, nullable=True)
    #metadata tags
    tags = Column(JSONB, nullable=True)
    #intelligence metadata extracted by V3 workers
    detected_objects = Column(JSONB, nullable=True, default=list)
    scene_label = Column(String(100), nullable=True)
    time_label = Column(String(100), nullable=True)
    environment_label = Column(String(100), nullable=True)
    processed_at = Column(DateTime(timezone=True), nullable=True)
    ranking_score = Column(Float, nullable=False, default=0.0)
    #timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())
